spring:
  datasource:
    url: jdbc:postgresql://monorail.proxy.rlwy.net:25236/railway
    username: postgres
    password: mQevBddhwPOiAjVIxsOTOVrRrDmhLuqY
    driver-class-name: org.postgresql.Driver

  security:
    jwt:
      public-key-path: classpath:app.pub
      private-key-path: classpath:app.key
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect